### PR TITLE
An alternative coloring of your amazing theme.

### PR DESCRIPTION
**Pull request by S4deghN**
I have use your theme for quite a while and edited some colorings the way I liked it more. 
you could add it as an alternative version.

### CODE REVIEW

**Comment by taunoe** [comment]
Thank you! I will test it and when I like it I will merge it.

**Comment by taunoe** [comment]
I like colours, but I think it should use monospace fonts. Otherwise, it messes up text alignment: [Screenshot](https://ibb.co/NCPpRVL). I will merge it later, but I will change the fonts.

**Comment by S4deghN** [comment]
Oh, but I don't have this problem. maybe because I have modified my preference.txt file a while ago and set the editor font to Consolas and it overrides it. not sure. honestly I have done this modification of your project a long time ago and don't remember the details. 
Here is how it is on my system: [Screenshot](https://pasteboard.co/JWgmlR0.png)
Here is my preference.txt file content for editor: 
```
editor.antialias=true
editor.auto_close_braces=true
editor.caret.blink=true
editor.code_folding=false
editor.divider.size=2
editor.external=false
editor.font=consolas,plain,17
editor.indent=true
editor.invalid=false
editor.keys.alternative_cut_copy_paste=true
editor.keys.home_and_end_beginning_end_of_doc=false
editor.keys.shift_backspace_is_delete=true
editor.languages.current=
editor.linenumbers=true
editor.save_on_verify=true
editor.tabs.expand=true
editor.tabs.size=2
editor.update_extension=true
editor.window.height.default=600
editor.window.height.min=190
editor.window.width.default=500
editor.window.width.min=100
```
I hope this information help you fix it for everyone.
thank you for review.

**Comment by taunoe** [comment]
Yes, of course, the problem is that these fonts are not in my system.

**Comment by S4deghN** [comment]
Awesome, I tested the merged version on my system too and it works all fine. It just needs an update for the screenshots. 
I recommend to use Consolas font for them. In general Consolas looks a lot better than other fonts on Arduino.

**Pull request merged**
